// <auto-generated />
using System;
using Chatter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Chatter.Migrations
{
    [DbContext(typeof(ChatterContext))]
    [Migration("20190726030433_updateBoards")]
    partial class updateBoards
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Chatter.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BoardIdId");

                    b.Property<string>("Content");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("BoardIdId");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("Chatter.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Topic");

                    b.HasKey("Id");

                    b.ToTable("Board");
                });

            modelBuilder.Entity("Chatter.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BlogIdId");

                    b.Property<string>("userName");

                    b.HasKey("Id");

                    b.HasIndex("BlogIdId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Chatter.Models.Blog", b =>
                {
                    b.HasOne("Chatter.Models.Board", "BoardId")
                        .WithMany("BlogId")
                        .HasForeignKey("BoardIdId");
                });

            modelBuilder.Entity("Chatter.Models.User", b =>
                {
                    b.HasOne("Chatter.Models.Blog", "BlogId")
                        .WithMany()
                        .HasForeignKey("BlogIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
